// Generated by CoffeeScript 1.9.2
var fs, http, sendFile, server;

http = require('http');

fs = require('fs');

server = http.createServer();

server.on('request', function(req, res) {
  var file;
  switch (req.url) {
    case '/':
      file = new fs.ReadStream('./public/chat_page.html');
      return sendFile(file, res);
    default:
      res.statusCode = 404;
      return res.end("Page not found");
  }
});

server.listen(8099, '127.0.0.1');

console.log("Server is running");

sendFile = function(file, res) {
  file.pipe(res);
  file.on('error', function(err) {
    res.statusCode = 500;
    res.end('Server error');
    return console.error(err);
  });
  file.on('open', function() {
    return console.log('open');
  }).on('close', function() {
    return console.log("close");
  });
  return res.on('close', function() {
    return file.destroy();
  });
};
